version: '3.8'

services:
  db:
    build: ./database
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  web:
    build: .
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./my-portfolio:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge